openapi: 3.0.0
info:
  version: 1.0.0
  title: Order Service API
  description: Open API with JSON schema test

servers:
  - url: http://localhost:4000

#https://swagger.io/docs/specification/authentication/bearer-authentication/
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: Bearer <JWT>

paths:
  /orders:
    post:
      security:
        - jwtAuth: [admin]
      description: create order
      summary: /orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ./schemas/orders/CreateOrderPayload.json

      responses:
        '201':
          description: Successful
          content:
            application/json:
              schema:
                $ref: './schemas/orders/CreateOrderResponse.json'

  /orders/{orderId}:
    get:
      description: get order by id
      summary: /orders/{orderId}
      parameters:
        - in: path
          name: orderId
          schema:
            $ref: './schemas/orders/Order.json#/properties/id'
          required: true

      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: './schemas/orders/GetOrderResponse.json'
